CREATE TABLE IF NOT EXISTS profile
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname VARCHAR(10) NOT NULL,
    phone    INT         NOT NULL,
    email    VARCHAR(30),
    avatar   VARCHAR(512),
    address  VARCHAR(512),
    is_deleted SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN profile.avatar IS 'user''s avatar url';
COMMENT ON COLUMN profile.address IS 'user''s delivery address, nullable';

CREATE TRIGGER trigger_set_updated_at
    BEFORE UPDATE ON profile
    FOR EACH ROW
EXECUTE PROCEDURE update_updated_at_column();


