CREATE TABLE IF NOT EXISTS gomall_user
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50)   NOT NULL,
    password   VARCHAR(1024) NOT NULL,
    status     SMALLINT      NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_user_username UNIQUE (username),
    CONSTRAINT ck_user_status CHECK (status IN (0, 1))
);

COMMENT ON COLUMN gomall_user.password IS 'encrypted password(hash)';
COMMENT ON COLUMN gomall_user.status IS 'user status: 1 -> normal, 0 -> banned';

CREATE TRIGGER trigger_set_updated_at
    BEFORE UPDATE ON gomall_user
    FOR EACH ROW
EXECUTE PROCEDURE update_updated_at_column();

CREATE TABLE IF NOT EXISTS gomall_role
(
    id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    code       VARCHAR(10) NOT NULL,
    name       varchar(10) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_role_code UNIQUE (code)
);

COMMENT ON COLUMN gomall_role.code IS 'unique code for a role';
COMMENT ON COLUMN gomall_role.name IS 'Chinese name for a role';

CREATE TRIGGER trigger_set_updated_at
    BEFORE UPDATE ON gomall_role
    FOR EACH ROW
EXECUTE PROCEDURE update_updated_at_column();

CREATE TABLE IF NOT EXISTS gomall_permission
(
    id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    code       VARCHAR(20) NOT NULL,
    resource   VARCHAR(10) NOT NULL,
    action     VARCHAR(10) NOT NULL,
    name       VARCHAR(10),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_permission_code UNIQUE (code)
);

COMMENT ON COLUMN gomall_permission.code IS 'unique code for a permission';
COMMENT ON COLUMN gomall_permission.name IS 'Chinese name for a permission';

CREATE TRIGGER trigger_set_updated_at
    BEFORE UPDATE ON gomall_permission
    FOR EACH ROW
EXECUTE PROCEDURE update_updated_at_column();

CREATE TABLE IF NOT EXISTS user_role
(
    user_id    BIGINT      NOT NULL,
    role_id    BIGINT      NOT NULL,
    granted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_user_role_user_id FOREIGN KEY (user_id) REFERENCES gomall_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_role_role_id FOREIGN KEY (role_id) REFERENCES gomall_role (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS role_permission
(
    role_id       BIGINT      NOT NULL,
    permission_id BIGINT      NOT NULL,
    granted_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_role_permission_role_id FOREIGN KEY (role_id) REFERENCES gomall_role (id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permission_permission_id FOREIGN KEY (permission_id) REFERENCES gomall_permission (id) ON DELETE CASCADE
);

CREATE INDEX idx_rbac_user_role_role_id
    ON user_role (role_id);

CREATE INDEX idx_rbac_role_permission_permission_id
    ON role_permission (permission_id);