server:
  port: 8081

database:
  connection:
    host: 127.0.0.01
    port: 5432
  user: postgres
  password: root
  db: auth_db

jwt:
  secret-key: your_secret_key
  expiration: 600
  refresh-expiration: 3600