CREATE TABLE IF NOT EXISTS shop
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id    BIGINT        NOT NULL,
    name        VARCHAR(255)  NOT NULL,
    description VARCHAR(1024) NOT NULL,
    -- 0: normal; 1: banned
    is_banned   SMALLINT      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_shop_is_banned CHECK ( is_banned IN (0, 1))
);

CREATE INDEX idx_shop_owner_id ON shop (owner_id);

CREATE TRIGGER trigger_set_updated_at
    BEFORE UPDATE
    ON shop
    FOR EACH ROW
EXECUTE PROCEDURE update_updated_at_column();