CREATE TABLE IF NOT EXISTS sku_stock
(
    sku_id BIGINT NOT NULL PRIMARY KEY ,
    available_qty BIGINT NOT NULL DEFAULT 0,
    locked_qty BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_available_qty CHECK ( available_qty > 0 ),
    CONSTRAINT ck_locked_qty CHECK ( locked_qty > 0 )
);

COMMENT ON COLUMN sku_stock.available_qty IS 'current available stock';
COMMENT ON COLUMN sku_stock.locked_qty IS 'the stock that had been reserved by user';

CREATE TRIGGER trigger_set_updated_at
    BEFORE UPDATE
    ON sku_stock
    FOR EACH ROW
EXECUTE PROCEDURE update_updated_at_column();

CREATE TABLE IF NOT EXISTS stock_reservation
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    order_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    quantity BIGINT NOT NULL CHECK ( quantity > 0 ),
    status VARCHAR(32) NOT NULL DEFAULT 'reserved',

    expired_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_status CHECK ( status IN ('reserved', 'confirmed', 'released') ),
    UNIQUE (order_id, sku_id)
);
