CREATE TABLE IF NOT EXISTS product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200) NOT NULL,
    shop_id     BIGINT       NOT NULL,
    description VARCHAR(1024),
    status      SMALLINT     NOT NULL DEFAULT 1,
    created_at  TIMESTAMPTZ           DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ           DEFAULT CURRENT_TIMESTAMP,

    -- 1: In stock; 0: Out of stock
    CONSTRAINT ck_product_status CHECK ( status IN (0, 1))
);

CREATE TRIGGER trigger_set_updated_at
    BEFORE UPDATE
    ON product
    FOR EACH ROW
EXECUTE PROCEDURE update_updated_at_column();

COMMENT ON COLUMN product.shop_id IS 'shop''s id for what the product belonged to';

CREATE INDEX idx_shop_id ON product (shop_id);

CREATE TABLE IF NOT EXISTS sku
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    BIGINT       NOT NULL,
    price         int          NOT NULL,
    specification VARCHAR(255) NOT NULL,
    created_at    TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_sku_product_id FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE
);



